file_format: "1"
id: zboard
name: Zboard
type: shield
url: https://github.com/oldmanz/zmk-zboard
requires: [pro_micro]
exposes: []
features:
  - keys
siblings:
  - zboard_left
  - zboard_right